# Generated by Django 4.1.3 on 2023-04-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelStud',
            new_name='ModelStudent',
        ),
    ]
