# Generated by Django 4.1.3 on 2023-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_rename_modelstud_modelstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
