# Generated by Django 4.1.3 on 2023-05-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_alter_modelstudent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelstudent',
            name='id',
        ),
        migrations.AddField(
            model_name='modelstudent',
            name='registration_number',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
