# Generated by Django 4.1.3 on 2023-05-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0004_remove_modelstudent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstudent',
            old_name='registration_number',
            new_name='id',
        ),
    ]
