# Generated by Django 4.1.3 on 2023-05-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0005_rename_registration_number_modelstudent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstudent',
            old_name='id',
            new_name='regid',
        ),
    ]
